#!/bin/bash

# Upload Latest Code to Production
# This script helps upload the latest code to your production server

echo "📤 Uploading Latest Code to Production..."
echo "======================================="

PRODUCTION_HOST="51.79.254.237"

echo "📋 Files to upload:"
echo "   - API source code (src/)"
echo "   - API configuration files"
echo "   - Admin frontend source code"
echo "   - Admin configuration files"
echo ""

echo "🔧 Manual upload commands:"
echo ""
echo "API Files:"
echo "scp -r src/ root@$PRODUCTION_HOST:/root/moviesite-web/apps/api/"
echo "scp package.json root@$PRODUCTION_HOST:/root/moviesite-web/apps/api/"
echo "scp package-lock.json root@$PRODUCTION_HOST:/root/moviesite-web/apps/api/"
echo "scp tsconfig.json root@$PRODUCTION_HOST:/root/moviesite-web/apps/api/"
echo "scp -r prisma/ root@$PRODUCTION_HOST:/root/moviesite-web/apps/api/"
echo ""
echo "Admin Files:"
echo "scp -r ../admin/src/ root@$PRODUCTION_HOST:/root/moviesite-web/apps/admin/"
echo "scp ../admin/package.json root@$PRODUCTION_HOST:/root/moviesite-web/apps/admin/"
echo "scp ../admin/package-lock.json root@$PRODUCTION_HOST:/root/moviesite-web/apps/admin/"
echo "scp ../admin/next.config.mjs root@$PRODUCTION_HOST:/root/moviesite-web/apps/admin/"
echo "scp ../admin/tailwind.config.ts root@$PRODUCTION_HOST:/root/moviesite-web/apps/admin/"
echo "scp ../admin/tsconfig.json root@$PRODUCTION_HOST:/root/moviesite-web/apps/admin/"
echo ""

echo "🚀 After uploading, run these commands on production:"
echo ""
echo "ssh root@$PRODUCTION_HOST"
echo ""
echo "# Update API"
echo "cd /root/moviesite-web/apps/api"
echo "npm install"
echo "npm run build"
echo "npx prisma generate"
echo "npx prisma db push"
echo "pm2 restart api"
echo ""
echo "# Update Admin"
echo "cd /root/moviesite-web/apps/admin"
echo "npm install"
echo "npm run build"
echo "pm2 restart admin"
echo ""
echo "🧪 Test the deployment:"
echo "curl http://$PRODUCTION_HOST:4000/health"
echo "curl -I http://$PRODUCTION_HOST:3001/"
echo ""
echo "🌐 Your updated services will be available at:"
echo "   Frontend: http://$PRODUCTION_HOST:3001/"
echo "   API: http://$PRODUCTION_HOST:4000/"

